name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node:
    name: Run tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm test
